version: "3.9"

services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - tf_serving_model
    volumes:
      - ./app:/app
    restart: always

  tf_serving_model:
    image: tensorflow/serving
    ports:
      - "8500:8500"
    volumes:
      - ./saved_model:/models/ED
    environment:
      - MODEL_NAME=ED
    restart: always
